from os import listdir, makedirs
import json

def module_type_checker(module):
    if module['type'] == "std":
        return 1
    if module['type'] == "func":
        return 2
    if module['type'] == "args":
        return 3

build_order = None

with open("build-order.json", "r") as f:
    file = f.read()
    build_order = json.loads(file)

makedirs("dist", exist_ok=True)

for alias_name, alias_modules in build_order.items():
    print(f"Building {alias_name}...")
    with open(f"dist/{alias_name}.alias", "w") as alias:
        alias.write("<drac2>\n\n")
        alias.write("##############################\n")
        alias.write("# This code is autogenerated #\n")
        alias.write(f"# The alias name is \"{alias_name}\"    #\n")
        alias.write("##############################\n\n")
        for module in alias_modules:
            match module_type_checker(module):
                case 1:
                    # standard module
                    with open(module['path'], "r") as std:
                        print(f"Adding standard module: {module['name']}...")
                        alias.write("#"*len(f"# Standard Module: {module['name']} #") + "\n")
                        alias.write(f"# Standard Module: {module['name']} #\n")
                        alias.write("#"*len(f"# Standard Module: {module['name']} #") + "\n")
                        alias.write(std.read() + "\n")
                        alias.write("\n")
                case 2:
                    # function module
                    with open(module['path'], "r") as func:
                        print(f"Adding function module: {module['name']}...")
                        alias.write("#"*len(f"# Function Module: {module['name']} #") + "\n")
                        alias.write(f"# Function Module: {module['name']} #\n")
                        alias.write("#"*len(f"# Function Module: {module['name']} #") + "\n")
                        alias.write(f"def {module['func_name']}():\n")
                        while True:
                            line = func.readline()
                            if not line:
                                break
                            alias.write("\t" + line)
                        alias.write("\n\n")
                case 3:
                    # function with arguments module
                    with open(module['path'], "r") as args:
                        print(f"Adding function with arguments module: {module['name']}...")
                        alias.write("#"*len(f"# Function Module: {module['name']} #") + "\n")
                        alias.write(f"# Function Module: {module['name']} #\n")
                        alias.write("#"*len(f"# Function Module: {module['name']} #") + "\n")
                        alias.write(f"def {module['func_name']}(")
                        alias.write(", ".join(module['args']))
                        alias.write("):\n")
                        while True:
                            line = args.readline()
                            if not line:
                                break
                            alias.write("\t" + line)
                        alias.write("\n\n")
        alias.write(f"# End of auto generated section\n")
        alias.write(f"# You can add your custom code below this line\n")
        alias.write("\n\n\n")
        alias.write("</drac2>\n")