from os import listdir, makedirs
import json

TAB = "    "
NEWLINE = "\n"

build_order = None

with open("build-order.json", "r") as f:
    file = f.read()
    build_order = json.loads(file)

makedirs("dist", exist_ok=True)

for key, value in build_order.items():
    print(f"Building {key}...")
    with open(f"dist/{key}.alias", "w") as alias:
        alias.write(f"# This alias is autogenerated\n")
        alias.write(f"# This alias name is {key}\n")
        for module in value:
            print(f"Adding module {module['path']} as {module['type']} type...")
            with open(f"{module["path"]}", "r") as f:
                file = f.read()
                alias.write(file)
                alias.write(NEWLINE)
        pass