name: Build & Release Alias

on:
  push:
    tags:
      - "v*" # trigger when you push a tag like v1.0.0

jobs:
  build:
    runs-on: docker
    container:
      image: python:3.12-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Run build script
        run: |
          python build.py

      - name: Verify output
        run: ls -R dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
