name: Build & Release Nightly Alias

on:
  push:

jobs:
  build:
    runs-on: docker
    container:
      image: ubuntu:22.04
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-pip nodejs npm

      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          python3 build.py

      - name: Verify output
        run: ls -R dist

      - name: Create Release
        uses: actions/forgejo-release@v2.11.1
        with:
          direction: upload
          token: ${{ secrets.WRITE_TOKEN }}
          release-dir: dist
          title: "Nightly release"