name: Build & Release Nightly Alias

on:
  push:

jobs:
  build:
    runs-on: docker
    container:
      image: alpine:latest
    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache \
            nodejs \
            npm \
            git \
            python3 \
            py3-pip \
            py3-setuptools

      - uses: actions/checkout@v4

      - name: Run build script
        run: |
          python3 build.py

      - name: Verify output
        run: ls -R dist

      - name: Create Release
        uses: https://code.forgejo.org/actions/forgejo-release@v2.11.0
        with:
          direction: upload
          token: ${{ secrets.WRITE_TOKEN }}
          release-dir: dist
          title: "Nightly release"