name: Build & Release Nightly Alias

on:
  push:

jobs:
  build:
    runs-on: docker
    container:
      image: alpine:latest
    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache \
            git \
            nodejs \
            npm \
            python3 \
            py3-pip

      - name: Check out repository
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Run build script
        run: |
          python build.py

      - name: Verify output
        run: ls -R dist

      - name: Create Release
        uses: actions/upload-artifact@v7
        with:
          #direction: upload
          #token: ${{ secrets.WRITE_TOKEN }}
          path: dist/